package com.github.cesar1287.pingpongx.utils

object Constants {

    const val KEY_RESULT_EXTRA_PLAYER_HOME_NAME = "KEY_RESULT_EXTRA_PLAYER_HOME_NAME"
    const val KEY_RESULT_EXTRA_PLAYER_AWAY_NAME = "KEY_RESULT_EXTRA_PLAYER_AWAY_NAME"
    const val KEY_RESULT_EXTRA_PLAYER_HOME_SCORE = "KEY_RESULT_EXTRA_PLAYER_HOME_SCORE"
    const val KEY_RESULT_EXTRA_PLAYER_AWAY_SCORE = "KEY_RESULT_EXTRA_PLAYER_AWAY_SCORE"
}